### ISSUE TITLE
[Discussion] Source for Tracestack Topo map

### ISSUE THREAD

**Issue by eddy-geek** [tracestrack/tracesmap.com#2]
Hello, is there a source for the theme/rendering pipeline used for the Tracestack Topo map?

I'm interested in contributing better elevation contour lines for the Alps.

Thanks

**Comment by quinncnl** [comment]
Hi @eddy-geek , the Topo basemap is open sourced here: https://github.com/tracestrack/tracestrack-maps. The label layer is currently closed-source.

**Comment by eddy-geek** [comment]
great to see you're open-sourcing this :)

I see on https://en.osm.town/@tracestrack/ that you're actively improving contour lines quality, great as well :)

if you already have a pipeline on your server for aggregating those multiple DEM data, then maybe it would be easy for you to add those more detailed DEM for the alps? I have compiled them from local datasources (all opendata, see licenses at the bottom of the page) in my **[eslope](https://github.com/eslopemap/eslope) project** (look for the `DTM.tif` column in the table)

Of course tell me if I can do anything to help. Right now it totals 40gb of data but I could downsample it.

**Comment by quinncnl** [comment]
Thanks for slope DEM! Will check how can we use it.
