### ISSUE TITLE
[Topo] summit names missing

### ISSUE THREAD

**Issue by eddy-geek** [tracestrack/tracesmap.com#3]
Mountain summits, and lakes, are missing at most (lower) zoom-levels, leading to very empty maps in wilder areas.

Example in France:

https://mc.bbbike.org/mc/?lon=7.533939&lat=44.113688&zoom=11&num=4&mt0=mapnik-german&mt1=outdooractive-summer-osm&mt2=tracestrack-topo

![image](https://github.com/tracestrack/tracesmap.com/assets/2772505/beb8ddf6-68ec-4ea6-9f5c-23c209526e84)

**Comment by quinncnl** [comment]
The problem is with so many peaks with names in lower zoom, some peak will be hidden. That's why only elevation is shown. It would be better to show some important peak names at lower zoom. Is there a good way to determine which peak names should be shown in lower zoom?

**Comment by eddy-geek** [comment]
it's a good point. I'm no expert, but I can think of **[prominence](https://wiki.openstreetmap.org/wiki/Key:prominence)** as a posible tool. *"Topographic prominence is a objective measurement of how significant a peak is. For example, lists of tallest mountains use a minimum prominence cutoff of 100, 200 or 300 meters to define an independent peak. In general, all peaks with very high prominence (over 1500 meters) are important mountains. But not all important peaks have high prominence. **Prominence might be used to select peaks for rendering**,  or to select significant peaks for analysis by database users. A scheme which can work both for Denmark and Switzerland, would be: If too many peaks are present within a particular area of the map at a certain zoom level, select the ones with highest prominence. Different thresholds might be used for when to render a peak symbol only, versus render the peak with a name label or elevation. "*

[Openstreetmap](https://www.openstreetmap.org/node/26863010),  [wikidata](https://www.wikidata.org/wiki/Q1372), [peaklist](http://www.peaklist.org/lists.html) could be sources with varying coverage otherwise it has to be computed from DEM.

OpenTopoMap seems [to use a geographic **isolation**](https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/tools/isolation.c) system, that seems easier to compute and may give a more homogeneous density?

(I guess presence of the summit on Wikipedia, Wikidata, hikr.org, camptocamp etc. could also be used to assess popularity, but with high risk of local variation in quality)

**Comment by quinncnl** [comment]
Hi @eddy-geek good stuff. `prominence` can definitely be used here. It looks like popular peaks tend to have more tags. I'll come up with a test ranking and map based on prominence and number of tags. If that doesn't work well then I'll explore third party data set and DEM based algorithm.

**Comment by quinncnl** [comment]
The new solution is described here: https://github.com/tracestrack/tracestrack-maps/issues/7#issuecomment-1826286852

Let's see how it works after rerendering!
