### ISSUE TITLE
Intersection poorly rendered in London

### ISSUE THREAD

**Issue by DavidKarlas** [tracestrack/tracesmap.com#4]
Problem appears when zoomed in:
![image](https://github.com/tracestrack/tracesmap.com/assets/774791/bd54b310-a460-4095-b22e-3d1c924910ba)
When zoomed out it is fine:
![image](https://github.com/tracestrack/tracesmap.com/assets/774791/18b9bf43-420d-4bf8-8a6c-5b2e690ae783)

Location:
https://tracesmap.com/#19/51.5355/0.1030

**Comment by quinncnl** [comment]
Hi @DavidKarlas , we got similar report here https://en.osm.town/@tracestrack/111212320735937099. The database were reimported and now it should be good.
