### ISSUE TITLE
[Carto/Topo] Incorrect country-specific shields in Spain: A- roads

### ISSUE THREAD

**Issue by Robot8A** [tracestrack/tracesmap.com#5]
In Spain roads which start with A- can be motorways and have a shield blue background and white font, as stated on Tracestrack Topo.
However, some of the roads which start with A- are not motorways, and are rather regional roads from Aragón or Andalucía, or provincial roads from Araba/Álava. Please take a look here: https://es.wikipedia.org/wiki/Red_de_carreteras_de_Espa%C3%B1a and at each of the affected regions numbering systems.
This can be seen in places like https://tracesmap.com/#13/41.5384/-1.1816, where only the motorway A-2 should have a blue shield.

I suggest as a quick fix to only show blue shields at roads tagged highway=motorway.

**Comment by 1ec5** [comment]
The Spanish community tags the route colors in [`ref:colour`](https://wiki.openstreetmap.org/wiki/Key:ref:colour), on both the roadway and the route relation.

/ref ZeLonewolf/openstreetmap-americana#654

**Comment by quinncnl** [comment]
> I suggest as a quick fix to only show blue shields at roads tagged highway=motorway.

This is an easy fix and done. We are thinking to open source shields related codes for everyone to collaborate on it.

> The Spanish community tags the route colors in [ref:colour](https://wiki.openstreetmap.org/wiki/Key:ref:colour), on both the roadway and the route relation.

This can be used in a separate layer (e.g. https://tracesmap.com/#14/40.4155/-3.7122/subway). For an more complex maps we still need to tune the color to match the base maps.

**Comment by quinncnl** [comment]
Ticket for country specific shields: https://github.com/tracestrack/tracestrack-maps/issues/12
